package net.radzebra.itTalent.dao;

public class ConfidentLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confident_level.ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confident_level.desc
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confident_level.ID
     *
     * @return the value of confident_level.ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confident_level.ID
     *
     * @param id the value for confident_level.ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column confident_level.desc
     *
     * @return the value of confident_level.desc
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column confident_level.desc
     *
     * @param desc the value for confident_level.desc
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}