package net.radzebra.itTalent.dao;

import java.util.List;
import net.radzebra.itTalent.dao.ConfidentLevel;
import net.radzebra.itTalent.dao.ConfidentLevelExample;
import org.apache.ibatis.annotations.Param;

public interface ConfidentLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int countByExample(ConfidentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int deleteByExample(ConfidentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insert(ConfidentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insertSelective(ConfidentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    List<ConfidentLevel> selectByExample(ConfidentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    ConfidentLevel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExampleSelective(@Param("record") ConfidentLevel record, @Param("example") ConfidentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExample(@Param("record") ConfidentLevel record, @Param("example") ConfidentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByPrimaryKeySelective(ConfidentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confident_level
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByPrimaryKey(ConfidentLevel record);
}