package net.radzebra.itTalent.dao;

import java.util.List;
import net.radzebra.itTalent.dao.Contact;
import net.radzebra.itTalent.dao.ContactExample;
import org.apache.ibatis.annotations.Param;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int countByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int deleteByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    List<Contact> selectByExample(ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExampleSelective(@Param("record") Contact record, @Param("example") ContactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExample(@Param("record") Contact record, @Param("example") ContactExample example);
}