package net.radzebra.itTalent.dao;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String talentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.talent_ID
     *
     * @return the value of contact.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getTalentId() {
        return talentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.talent_ID
     *
     * @param talentId the value for contact.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setTalentId(String talentId) {
        this.talentId = talentId == null ? null : talentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.desc
     *
     * @return the value of contact.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.desc
     *
     * @param desc the value for contact.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}