package net.radzebra.itTalent.dao;

public class Endorsement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.talent_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String talentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.story_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String storyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.endorser_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String endorserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.endorser_comment
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String endorserComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column endorsement.desc
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.ID
     *
     * @return the value of endorsement.ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.ID
     *
     * @param id the value for endorsement.ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.talent_ID
     *
     * @return the value of endorsement.talent_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getTalentId() {
        return talentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.talent_ID
     *
     * @param talentId the value for endorsement.talent_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setTalentId(String talentId) {
        this.talentId = talentId == null ? null : talentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.story_ID
     *
     * @return the value of endorsement.story_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getStoryId() {
        return storyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.story_ID
     *
     * @param storyId the value for endorsement.story_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setStoryId(String storyId) {
        this.storyId = storyId == null ? null : storyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.endorser_ID
     *
     * @return the value of endorsement.endorser_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getEndorserId() {
        return endorserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.endorser_ID
     *
     * @param endorserId the value for endorsement.endorser_ID
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setEndorserId(String endorserId) {
        this.endorserId = endorserId == null ? null : endorserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.endorser_comment
     *
     * @return the value of endorsement.endorser_comment
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getEndorserComment() {
        return endorserComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.endorser_comment
     *
     * @param endorserComment the value for endorsement.endorser_comment
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setEndorserComment(String endorserComment) {
        this.endorserComment = endorserComment == null ? null : endorserComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column endorsement.desc
     *
     * @return the value of endorsement.desc
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column endorsement.desc
     *
     * @param desc the value for endorsement.desc
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}