package net.radzebra.itTalent.dao;

import java.util.ArrayList;
import java.util.List;

public class EndorsementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public EndorsementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTalentIdIsNull() {
            addCriterion("talent_ID is null");
            return (Criteria) this;
        }

        public Criteria andTalentIdIsNotNull() {
            addCriterion("talent_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTalentIdEqualTo(String value) {
            addCriterion("talent_ID =", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdNotEqualTo(String value) {
            addCriterion("talent_ID <>", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdGreaterThan(String value) {
            addCriterion("talent_ID >", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdGreaterThanOrEqualTo(String value) {
            addCriterion("talent_ID >=", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdLessThan(String value) {
            addCriterion("talent_ID <", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdLessThanOrEqualTo(String value) {
            addCriterion("talent_ID <=", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdLike(String value) {
            addCriterion("talent_ID like", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdNotLike(String value) {
            addCriterion("talent_ID not like", value, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdIn(List<String> values) {
            addCriterion("talent_ID in", values, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdNotIn(List<String> values) {
            addCriterion("talent_ID not in", values, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdBetween(String value1, String value2) {
            addCriterion("talent_ID between", value1, value2, "talentId");
            return (Criteria) this;
        }

        public Criteria andTalentIdNotBetween(String value1, String value2) {
            addCriterion("talent_ID not between", value1, value2, "talentId");
            return (Criteria) this;
        }

        public Criteria andStoryIdIsNull() {
            addCriterion("story_ID is null");
            return (Criteria) this;
        }

        public Criteria andStoryIdIsNotNull() {
            addCriterion("story_ID is not null");
            return (Criteria) this;
        }

        public Criteria andStoryIdEqualTo(String value) {
            addCriterion("story_ID =", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdNotEqualTo(String value) {
            addCriterion("story_ID <>", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdGreaterThan(String value) {
            addCriterion("story_ID >", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("story_ID >=", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdLessThan(String value) {
            addCriterion("story_ID <", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdLessThanOrEqualTo(String value) {
            addCriterion("story_ID <=", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdLike(String value) {
            addCriterion("story_ID like", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdNotLike(String value) {
            addCriterion("story_ID not like", value, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdIn(List<String> values) {
            addCriterion("story_ID in", values, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdNotIn(List<String> values) {
            addCriterion("story_ID not in", values, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdBetween(String value1, String value2) {
            addCriterion("story_ID between", value1, value2, "storyId");
            return (Criteria) this;
        }

        public Criteria andStoryIdNotBetween(String value1, String value2) {
            addCriterion("story_ID not between", value1, value2, "storyId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdIsNull() {
            addCriterion("endorser_ID is null");
            return (Criteria) this;
        }

        public Criteria andEndorserIdIsNotNull() {
            addCriterion("endorser_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEndorserIdEqualTo(String value) {
            addCriterion("endorser_ID =", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdNotEqualTo(String value) {
            addCriterion("endorser_ID <>", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdGreaterThan(String value) {
            addCriterion("endorser_ID >", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdGreaterThanOrEqualTo(String value) {
            addCriterion("endorser_ID >=", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdLessThan(String value) {
            addCriterion("endorser_ID <", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdLessThanOrEqualTo(String value) {
            addCriterion("endorser_ID <=", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdLike(String value) {
            addCriterion("endorser_ID like", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdNotLike(String value) {
            addCriterion("endorser_ID not like", value, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdIn(List<String> values) {
            addCriterion("endorser_ID in", values, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdNotIn(List<String> values) {
            addCriterion("endorser_ID not in", values, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdBetween(String value1, String value2) {
            addCriterion("endorser_ID between", value1, value2, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserIdNotBetween(String value1, String value2) {
            addCriterion("endorser_ID not between", value1, value2, "endorserId");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentIsNull() {
            addCriterion("endorser_comment is null");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentIsNotNull() {
            addCriterion("endorser_comment is not null");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentEqualTo(String value) {
            addCriterion("endorser_comment =", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentNotEqualTo(String value) {
            addCriterion("endorser_comment <>", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentGreaterThan(String value) {
            addCriterion("endorser_comment >", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentGreaterThanOrEqualTo(String value) {
            addCriterion("endorser_comment >=", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentLessThan(String value) {
            addCriterion("endorser_comment <", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentLessThanOrEqualTo(String value) {
            addCriterion("endorser_comment <=", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentLike(String value) {
            addCriterion("endorser_comment like", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentNotLike(String value) {
            addCriterion("endorser_comment not like", value, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentIn(List<String> values) {
            addCriterion("endorser_comment in", values, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentNotIn(List<String> values) {
            addCriterion("endorser_comment not in", values, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentBetween(String value1, String value2) {
            addCriterion("endorser_comment between", value1, value2, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andEndorserCommentNotBetween(String value1, String value2) {
            addCriterion("endorser_comment not between", value1, value2, "endorserComment");
            return (Criteria) this;
        }

        public Criteria andDescIsNull() {
            addCriterion("desc is null");
            return (Criteria) this;
        }

        public Criteria andDescIsNotNull() {
            addCriterion("desc is not null");
            return (Criteria) this;
        }

        public Criteria andDescEqualTo(String value) {
            addCriterion("desc =", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotEqualTo(String value) {
            addCriterion("desc <>", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThan(String value) {
            addCriterion("desc >", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescGreaterThanOrEqualTo(String value) {
            addCriterion("desc >=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThan(String value) {
            addCriterion("desc <", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLessThanOrEqualTo(String value) {
            addCriterion("desc <=", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescLike(String value) {
            addCriterion("desc like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotLike(String value) {
            addCriterion("desc not like", value, "desc");
            return (Criteria) this;
        }

        public Criteria andDescIn(List<String> values) {
            addCriterion("desc in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotIn(List<String> values) {
            addCriterion("desc not in", values, "desc");
            return (Criteria) this;
        }

        public Criteria andDescBetween(String value1, String value2) {
            addCriterion("desc between", value1, value2, "desc");
            return (Criteria) this;
        }

        public Criteria andDescNotBetween(String value1, String value2) {
            addCriterion("desc not between", value1, value2, "desc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endorsement
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 01 16:14:24 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table endorsement
     *
     * @mbggenerated Thu Sep 01 16:14:24 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}