package net.radzebra.itTalent.dao;

import java.util.List;
import net.radzebra.itTalent.dao.Talent;
import net.radzebra.itTalent.dao.TalentExample;
import org.apache.ibatis.annotations.Param;

public interface TalentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int countByExample(TalentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int deleteByExample(TalentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int insert(Talent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int insertSelective(Talent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    List<Talent> selectByExample(TalentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    Talent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int updateByExampleSelective(@Param("record") Talent record, @Param("example") TalentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int updateByExample(@Param("record") Talent record, @Param("example") TalentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int updateByPrimaryKeySelective(Talent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    int updateByPrimaryKey(Talent record);
}