package net.radzebra.itTalent.dao;

import java.util.List;
import net.radzebra.itTalent.dao.TalentStory;
import net.radzebra.itTalent.dao.TalentStoryExample;
import net.radzebra.itTalent.dao.TalentStoryKey;
import org.apache.ibatis.annotations.Param;

public interface TalentStoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int countByExample(TalentStoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int deleteByExample(TalentStoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int deleteByPrimaryKey(TalentStoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insert(TalentStory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int insertSelective(TalentStory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    List<TalentStory> selectByExample(TalentStoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    TalentStory selectByPrimaryKey(TalentStoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExampleSelective(@Param("record") TalentStory record, @Param("example") TalentStoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByExample(@Param("record") TalentStory record, @Param("example") TalentStoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByPrimaryKeySelective(TalentStory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_story
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    int updateByPrimaryKey(TalentStory record);
}