package net.radzebra.itTalent.dao;

import java.util.List;
import net.radzebra.itTalent.dao.TalentTag;
import net.radzebra.itTalent.dao.TalentTagExample;
import org.apache.ibatis.annotations.Param;

public interface TalentTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int countByExample(TalentTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int deleteByExample(TalentTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int insert(TalentTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int insertSelective(TalentTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    List<TalentTag> selectByExample(TalentTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int updateByExampleSelective(@Param("record") TalentTag record, @Param("example") TalentTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table talent_tag
     *
     * @mbggenerated Sun Aug 14 20:25:37 CST 2011
     */
    int updateByExample(@Param("record") TalentTag record, @Param("example") TalentTagExample example);
}