package net.radzebra.itTalent.dao;

public class TalentStoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    private String talentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.story_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    private String storyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.talent_ID
     *
     * @return the value of talent_story.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public String getTalentId() {
        return talentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.talent_ID
     *
     * @param talentId the value for talent_story.talent_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public void setTalentId(String talentId) {
        this.talentId = talentId == null ? null : talentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.story_ID
     *
     * @return the value of talent_story.story_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public String getStoryId() {
        return storyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.story_ID
     *
     * @param storyId the value for talent_story.story_ID
     *
     * @mbggenerated Sun Aug 14 15:39:50 CST 2011
     */
    public void setStoryId(String storyId) {
        this.storyId = storyId == null ? null : storyId.trim();
    }
}