package net.radzebra.itTalent.dao;

public class Talent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.first_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.last_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.cell_phone
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String cellPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.email
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.birth_year
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String birthYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.birth_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String birthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.self_skill_desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String selfSkillDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.ID
     *
     * @return the value of talent.ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.ID
     *
     * @param id the value for talent.ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.name
     *
     * @return the value of talent.name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.name
     *
     * @param name the value for talent.name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.first_name
     *
     * @return the value of talent.first_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.first_name
     *
     * @param firstName the value for talent.first_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.last_name
     *
     * @return the value of talent.last_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.last_name
     *
     * @param lastName the value for talent.last_name
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.cell_phone
     *
     * @return the value of talent.cell_phone
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getCellPhone() {
        return cellPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.cell_phone
     *
     * @param cellPhone the value for talent.cell_phone
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setCellPhone(String cellPhone) {
        this.cellPhone = cellPhone == null ? null : cellPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.email
     *
     * @return the value of talent.email
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.email
     *
     * @param email the value for talent.email
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.birth_year
     *
     * @return the value of talent.birth_year
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getBirthYear() {
        return birthYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.birth_year
     *
     * @param birthYear the value for talent.birth_year
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setBirthYear(String birthYear) {
        this.birthYear = birthYear == null ? null : birthYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.birth_date
     *
     * @return the value of talent.birth_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.birth_date
     *
     * @param birthDate the value for talent.birth_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate == null ? null : birthDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.self_skill_desc
     *
     * @return the value of talent.self_skill_desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getSelfSkillDesc() {
        return selfSkillDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.self_skill_desc
     *
     * @param selfSkillDesc the value for talent.self_skill_desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setSelfSkillDesc(String selfSkillDesc) {
        this.selfSkillDesc = selfSkillDesc == null ? null : selfSkillDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent.desc
     *
     * @return the value of talent.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent.desc
     *
     * @param desc the value for talent.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}