package net.radzebra.itTalent.dao;

public class TalentStory extends TalentStoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.confident_level_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String confidentLevelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.type_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.start_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.end_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talent_story.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.confident_level_ID
     *
     * @return the value of talent_story.confident_level_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getConfidentLevelId() {
        return confidentLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.confident_level_ID
     *
     * @param confidentLevelId the value for talent_story.confident_level_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setConfidentLevelId(String confidentLevelId) {
        this.confidentLevelId = confidentLevelId == null ? null : confidentLevelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.type_ID
     *
     * @return the value of talent_story.type_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.type_ID
     *
     * @param typeId the value for talent_story.type_ID
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId == null ? null : typeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.start_date
     *
     * @return the value of talent_story.start_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.start_date
     *
     * @param startDate the value for talent_story.start_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.end_date
     *
     * @return the value of talent_story.end_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.end_date
     *
     * @param endDate the value for talent_story.end_date
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talent_story.desc
     *
     * @return the value of talent_story.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talent_story.desc
     *
     * @param desc the value for talent_story.desc
     *
     * @mbggenerated Sun Aug 14 15:41:57 CST 2011
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}